server:
  port: 8081
spring:
  application:
    name: hr-payment
hr-worker:
 ribbon:
  listOfServers: localhost:8080, localhost:9090
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true

