
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true
server:
  port: 8756
spring:
  application:
    name: hr-gateway

### CONFIGURATION ROUTES ####
zuul:
  routes:
    worker:
      service-id: hr-worker
      path: /hr-worker/**
    payment:
      service-id: hr-payment
      path: /hr-payment/**