
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true
server:
  port: 8756
spring:
  application:
    name: hr-gateway

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 1000000

ribbon:
  ConnectTimeout: 100000
  ReadTimeout: 200000

### CONFIGURATION ROUTES ####
zuul:
  routes:
    worker:
      service-id: hr-worker
      path: /hr-worker/**
    payment:
      service-id: hr-payment
      path: /hr-payment/**
    user:
      service-id: hr-user
      path: /hr-user/**
    oauth:
      service-id: hr-oauth
      path: /hr-oauth/**
      sensitive-headers: Cookie,Set-Cookie
