spring:
  application:
    name: hr-oauth
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true
server:
  port: 8084
security:
  oauth2:
    authorization:
      jwt:
        key-store-password: password