
spring:
  application:
    name: hr-user
  database: h2
  console: true
  path: /h2
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:h2:mem:rh-user
    username: sa
    password: sa
    driverClassName: org.h2.Driver
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true
server:
  port: 8083